/**
 * Converts plain text / markdown-ish LLM output into a proper .docx File.
 * Handles: # headings, **bold**, *italic*, bullet lists, numbered lists,
 * ALL-CAPS section titles (legal style), paragraph breaks.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  UnderlineType,
} from "docx";

// ── Inline markdown parser ─────────────────────────────────────
function parseInline(text: string): TextRun[] {
  const runs: TextRun[] = [];
  // Match **bold**, *italic*, __underline__, `code`, or plain text
  const re = /(\*\*[^*]+\*\*|\*[^*]+\*|__[^_]+__|`[^`]+`|[^*_`]+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    const t = m[0];
    if (t.startsWith("**") && t.endsWith("**"))
      runs.push(new TextRun({ text: t.slice(2, -2), bold: true }));
    else if (t.startsWith("*") && t.endsWith("*"))
      runs.push(new TextRun({ text: t.slice(1, -1), italics: true }));
    else if (t.startsWith("__") && t.endsWith("__"))
      runs.push(new TextRun({ text: t.slice(2, -2), underline: { type: UnderlineType.SINGLE } }));
    else if (t.startsWith("`") && t.endsWith("`"))
      runs.push(new TextRun({ text: t.slice(1, -1), font: "Courier New" }));
    else if (t)
      runs.push(new TextRun({ text: t }));
  }
  return runs.length ? runs : [new TextRun({ text })];
}

// ── Is a legal ALL-CAPS section title? ────────────────────────
function isAllCapsTitle(line: string): boolean {
  const trimmed = line.trim();
  return (
    trimmed.length > 3 &&
    trimmed === trimmed.toUpperCase() &&
    /[A-Z]/.test(trimmed) &&
    !trimmed.startsWith("•") &&
    !trimmed.match(/^\d/)
  );
}

// ── Main converter ─────────────────────────────────────────────
export async function textToDocx(text: string, title = "Legal Document"): Promise<File> {
  const lines = text.split("\n");
  const children: Paragraph[] = [];

  // Document title
  children.push(
    new Paragraph({
      text: title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    })
  );

  let i = 0;
  while (i < lines.length) {
    const raw  = lines[i];
    const line = raw.trim();
    i++;

    if (!line) {
      children.push(new Paragraph({ spacing: { after: 80 } }));
      continue;
    }

    // Markdown headings
    if (line.startsWith("### ")) {
      children.push(new Paragraph({ text: line.slice(4), heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 100 } }));
    } else if (line.startsWith("## ")) {
      children.push(new Paragraph({ text: line.slice(3), heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 120 }, border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "7C3AED" } } }));
    } else if (line.startsWith("# ")) {
      children.push(new Paragraph({ text: line.slice(2), heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 160 } }));

    // Horizontal rule
    } else if (line === "---" || line === "***" || line === "___") {
      children.push(new Paragraph({ border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "AAAAAA" } }, spacing: { before: 200, after: 200 } }));

    // Bullet list
    } else if (line.startsWith("- ") || line.startsWith("• ")) {
      children.push(new Paragraph({ bullet: { level: 0 }, children: parseInline(line.slice(2)), spacing: { after: 80 } }));

    // Numbered list
    } else if (/^\d+[\.)]\s/.test(line)) {
      const content = line.replace(/^\d+[\.)]\s/, "");
      children.push(new Paragraph({ children: [new TextRun({ text: `${content}` })], spacing: { after: 100 }, indent: { left: 360 } }));

    // ALL-CAPS legal section title
    } else if (isAllCapsTitle(line)) {
      children.push(new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 320, after: 120 },
        children: [new TextRun({ text: line, bold: true, allCaps: true, size: 24 })],
      }));

    // Regular paragraph with inline markdown
    } else {
      children.push(new Paragraph({ children: parseInline(line), spacing: { after: 120 } }));
    }
  }

  // Signature block footer
  children.push(
    new Paragraph({ spacing: { before: 600 }, border: { top: { style: BorderStyle.SINGLE, size: 4, color: "CCCCCC" } } }),
    new Paragraph({ children: [new TextRun({ text: "Generated by Draft@advoAI", color: "999999", size: 16 })], alignment: AlignmentType.RIGHT })
  );

  const doc = new Document({
    styles: {
      default: {
        document: { run: { font: "Calibri", size: 22 } },
      },
    },
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  const safeName = title.replace(/[^a-z0-9\s-]/gi, "").slice(0, 50).trim() || "document";
  return new File([blob], `${safeName}.docx`, {
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  });
}

// ── Detect if AI text is a legal document ─────────────────────
export function isLegalDocument(text: string, userPrompt = ""): boolean {
  if (text.length < 400) return false;
  const docPattern = /\b(AGREEMENT|CONTRACT|DEED|PETITION|APPLICATION|MEMORANDUM|AFFIDAVIT|UNDERTAKING|INDENTURE|WHEREAS|PARTY|PARTIES|CLAUSE|ARTICLE|WITNESSETH|IN WITNESS WHEREOF|THIS AGREEMENT|hereinafter|thereto|thereof|hereunder)\b/i;
  const draftPattern = /\b(draft|write|prepare|generate|create|make)\b.{0,60}(agreement|contract|deed|petition|application|affidavit|document|clause|writ|plaint)\b/i;
  return docPattern.test(text) || draftPattern.test(userPrompt);
}

// ── Extract a document title from first line ───────────────────
export function extractDocTitle(text: string): string {
  const firstLines = text.split("\n").slice(0, 5);
  for (const line of firstLines) {
    const clean = line.replace(/^#+\s*/, "").replace(/\*\*/g, "").trim();
    if (clean.length > 5 && clean.length < 100) return clean;
  }
  return "Legal Document";
}
